### ISSUE TITLE
DDTRH==0.0.4 | DDT 1.8 - Http404 for all other panels after update

### ISSUE THREAD

**Issue by julian-rachmann** [djsutho/django-debug-toolbar-request-history#11]
After upgrading to Django Debug Toolbar 1.8, all panels except Request History return Http404. Request History also does not return AJAX requests, even though I have the config set as per below:

```
DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': 'ddt_request_history.panels.request_history.allow_ajax',
}
```

**Comment by djsutho** [comment]
Looks like this broke with this PR https://github.com/jazzband/django-debug-toolbar/pull/926/files#diff-1afe11b3c00304da8da6fab291c6bad3R63 as the ajax check has been moved outside of the show toolbar callback.

To get non-ajax requests working again you can remove
```
'SHOW_TOOLBAR_CALLBACK': 'ddt_request_history.panels.request_history.allow_ajax',
``` 
Obviously this negates one of the main reasons to use this plugin.

It doesn't look like there will be a simple fix for this as I think I'll have monkey patch the `process_request` method of the `DebugToolbarMiddleware`.

Hopefully I'll be able to put some time into this soon.

**Comment by djsutho** [comment]
I've pushed up a new version that should work. Can you test with the master version by using 
```bash
pip install git+https://github.com/djsutho/django-debug-toolbar-request-history.git
```
You should no longer need to add `SHOW_TOOLBAR_CALLBACK` to the config but it should work either way.

**Comment by gtback** [comment]
@djsutho, the latest version of master works for me and allows me to view AJAX requests.

**Comment by julian-rachmann** [comment]
@djsutho Sorry for the delayed response, I somehow missed the notifications.

I've just tried again after upgrading back to 1.8 and running the command
```
pip install git+https://github.com/djsutho/django-debug-toolbar-request-history.git
``` 
PIP Freeze:
```
django-debug-toolbar==1.8
django-debug-toolbar-request-history==0.0.4
```

But I'm still getting the same result. No AJAX requests appear in the Request History tab, and all other tabs return Http404. 

If I take out the `SHOW_TOOLBAR_CALLBACK`, then the other tabs work, but still no AJAX requests in Request History.

**Comment by exp-dasutherland** [comment]
@julian-rachmann Can you try again with:
```
pip install -U git+https://github.com/djsutho/django-debug-toolbar-request-history.git
```

I forgot to add the -U flag in the instructions. I think you might still be on the old version.

**Comment by julian-rachmann** [comment]
Success! Thank you, it's working now.
